version: "2.1"

services:
  database:
    container_name: od-database
    build: database
    volumes:
      - ./database/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 5
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=postgres

  graphql:
    container_name: od-graphql
    build: graphql
    volumes:
      - ./graphql/package.json:/srv/package.json
      - ./graphql/yarn.lock:/srv/yarn.lock
      - ./graphql/src/:/srv/src/
    environment:
      - POSTGRES_DB_NAME=next
      - POSTGRES_DB_USER=postgres
      - POSTGRES_DB_PASSWORD=postgres
      - POSTGRES_DB_HOST=database
      - POSTGRES_DB_PORT=5432
      - ENABLE_GRAPHIQL=true
      - CORS_ORIGIN=http://localhost:5000
    depends_on:
      database:
        condition: service_healthy
    ports:
      - "5000:5000"

  proxy:
    container_name: od-proxy
    build: proxy
    volumes:
      - ./proxy/package.json:/srv/package.json
      - ./proxy/yarn.lock:/srv/yarn.lock
      - ./proxy/src/:/srv/src/
    environment:
      - GRAPHQL_ENDPOINT=http://od-graphql:5000/graphql
      - CACHE_EXPIRATION=1000
    depends_on:
      graphql:
        condition: service_started
    ports:
      - "5300:5300"

  frontend:
    container_name: od-frontend
    build: frontend
    volumes:
      - ./frontend/package.json:/srv/package.json
      - ./frontend/yarn.lock:/srv/yarn.lock
      - ./frontend/src/:/srv/src/
      - ./frontend/public/:/srv/public/
    depends_on:
      proxy:
        condition: service_started
    ports:
      - "3000:3000"
