name: build

on:
  push:
    branches:
      - OD-7-deploy-database-and-graphql-docker-containers-to-digital-ocean

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Publish GraphQl to Github Packages Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: open-discourse/open-discourse/graphql
          registry: docker.pkg.github.com
          username: ${{ secrets.DEPLOYMENT_USERNAME }}
          password: ${{ secrets.GITHUB_TOKEN }}
          dockerfile: graphql/Dockerfile
          tags: latest
      - name: Publish Database to Github Packages Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: open-discourse/open-discourse/graphql
          registry: docker.pkg.github.com
          username: ${{ secrets.DEPLOYMENT_USERNAME }}
          password: ${{ secrets.GITHUB_TOKEN }}
          dockerfile: database/Dockerfile
          tags: latest
