name: "Recreate Database"

on:
  push:
    branches: [OD-56-add-custom-runner]
  schedule:
    - cron: "0 0 1 * *"

jobs:
  setup:
    name: Setup environment
    runs-on: self-hosted

    steps:
      - run: cd ~/open-discourse/database && yarn
      - run: cd ~/open-discourse/python && sudo rm -rf .venv && chmod +x setup.sh && ./setup.sh
  build:
    name: Build
    runs-on: self-hosted
    needs: setup

    steps:
      - run: cd ~/open-discourse/python && chmod +x build.sh && ./build.sh
