name: "Recreate Database"

on:
  push:
    branches: [OD-56-add-custom-runner]
  schedule:
    - cron: "0 0 1 * *"

jobs:
  setup:
    name: Setup environment
    runs-on: self-hosted

    steps:
      - run: cd ~/open-discourse/database && yarn
      - run: cd ../python && sudo rm -rf .venv && ./setup.sh
  build:
    name: Build
    runs-on: self-hosted

    steps:
      - run: echo $PWD
